# Makefile for zabbix-nsx-t-exporter
# Minimal fork of upstream sapcc/nsx-t-exporter's autogenerated Makefile.

BINARY      := nsx-t-exporter
BUILD_DIR   := build
GO          ?= go
GOFLAGS     ?=
LDFLAGS     ?= -s -w
PKG         := ./...

.PHONY: all build run test vet lint clean fmt deps tidy help

all: build

build: $(BUILD_DIR)/$(BINARY) ## Build the exporter binary into build/

$(BUILD_DIR)/$(BINARY): $(shell find . -name '*.go' -not -path './vendor/*')
	@mkdir -p $(BUILD_DIR)
	$(GO) build $(GOFLAGS) -ldflags '$(LDFLAGS)' -o $@ .

run: build ## Run the binary (requires NSXV3_LOGIN_HOST/USER/PASSWORD env vars)
	$(BUILD_DIR)/$(BINARY)

test: ## Run unit tests
	$(GO) test -race -count=1 $(PKG)

vet: ## Run go vet
	$(GO) vet $(PKG)

lint: ## Run golangci-lint (must be installed separately)
	golangci-lint run

fmt: ## Run gofmt
	$(GO) fmt $(PKG)

deps: ## Download module dependencies
	$(GO) mod download

tidy: ## Tidy go.mod / go.sum
	$(GO) mod tidy

clean: ## Remove build artifacts
	rm -rf $(BUILD_DIR)

help: ## Show this help message
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  %-12s %s\n", $$1, $$2}' $(MAKEFILE_LIST)
